### PR TITLE
Small idea : Automate estimation of opponent's stats

### PR DESCRIPTION
**Pull request by GB127**
Still a WIP, but want to make sure it's welcome... And to seek guidance to fully implement this.

In summary, I created a function that will accept a HP damage (in the future, will use also a boolean value for crits), and returns the two possibles ends of an attack stats of the opponent's pokemon.

Here is what it *would display* following an attack (Read the commentary on the code for the exact scenario).

The placement of the informaiton is still subject to moves. Perhaps create an option to switch from boxes to those estimations?
image

### CODE REVIEW

**Comment by GB127** [comment]
Maybe use an input box and a Special /  Physical checkbox? So that the user still have to calculate the HP lost?

**Comment by valiant-code** [comment]
This is a level of automation that I think reaches too far into playing the game for you.

**Comment by bdjeffyp** [comment]
I agree with valiant-code on this. Automation regarding opponent Pokémon must be avoided, otherwise the challenge is reduced. Predictions are incumbent on the player to make rather than the code.

**Comment by bdjeffyp** [comment]
I agree with valiant-code on this. Automation regarding opponent Pokémon must be avoided, otherwise the challenge is reduced. Predictions are incumbent on the player to make rather than the code.

**Pull request closed without merging**
