### PR TITLE
No Power move ineffectiveness to certain Pokémon types

### PR DESCRIPTION
**Pull request by bdjeffyp**
As found in issue #48, Mirror Coat does not show that it is ineffective against Dark-type Pokémon.
This update allows for checking of moves that have no power stat, but do cause damage, to be checked if they are ineffective against specific Pokémon types.
Additionally, added a setting to disable showing move effectiveness if the player would rather not have that information.

### CODE REVIEW

**Comment by bdjeffyp** [comment]
Actually, I'm going to handle Mirror Coat as a special case completely. It shouldn't show it being super effective or not very effective except for Dark moves. So I will update this to just return 0 if the move.id matches.

**Comment by Tapollo** [comment]
@bdjeffyp looks like https://github.com/besteon/Ironmon-Tracker/issues/52 is similar.

**Comment by bdjeffyp** [comment]
@Tapollo, if you have a spot where you can verify that this stuff is working for you, would you mind testing the changes are working? Or you can email me offline with some save data so that I can test it myself?

**Comment by bdjeffyp** [comment]
Will be adding a check for SonicBoom in PR #51

**Comment by Tapollo** [comment]
@bdjeffyp I don't have that seed anymore. I have just been overwriting as I lose.

**Comment by bdjeffyp** [comment]
Ah well, it was a shot in the dark. Thanks for finding these edge cases though, @Tapollo! Now I just need to improve my toolset for testing out these changes better... 😅

**Comment by Tapollo** [comment]
@bdjeffyp I just got home. I thought of a way to test this out... with a bit of patience lol. I will just load of a see with three ghosts and keep checking the seeds till one has sonicboom. Then I will do the same for dark types and Mirror Coat. Do you have a copy with the fixes for me to try?

**Comment by bdjeffyp** [comment]
@Tapollo I appreciate you checking this out. If it is too much work, don't worry about it. You can download the change by going to https://github.com/besteon/Ironmon-Tracker/tree/user/bdjeffyp/ineffective-mirror-coat, click on the green "Code" button and selected "Download ZIP".

**Comment by Tapollo** [comment]
@bdjeffyp I have it downloaded and will start the testing now. I will report back with my findings.

**Comment by Tapollo** [comment]
[KaizoFR.zip](https://github.com/besteon/Ironmon-Tracker/files/8790483/KaizoFR.zip)

SonicBoom doesn't seem to be working. Here is a seed where the Gengar (Middle Choice) has SonicBoom.

image

**Comment by Tapollo** [comment]
@bdjeffyp 

[KaizoFR (2).zip](https://github.com/besteon/Ironmon-Tracker/files/8790503/KaizoFR.2.zip)

Here is an example of Mirror Coat not working. The Absol in the middle has Mirror Coat

image

**Comment by bdjeffyp** [comment]
This is great help! Thanks so much. I'll use this to fix the logic and get it right. I appreciate it!

**Comment by Tapollo** [comment]
@bdjeffyp Do you think that Counter would be affected in the same way against ghosts?

**Comment by bdjeffyp** [comment]
It's possible. The logic is set that any move that doesn't have a power stat is assumed to have default effectiveness so it doesn't do any further checks. We'll probably have to handle these edge cases one by one rather than programmatically.

**Comment by Tapollo** [comment]
@bdjeffyp 

[KaizoFR (3).zip](https://github.com/besteon/Ironmon-Tracker/files/8790545/KaizoFR.3.zip)

Here is an example of Endeavor not displaying that it doesn't work against Ghost types. The Gastly (Left Choice) has Endeavor.

image

**Comment by Tapollo** [comment]
@bdjeffyp 

[KaizoFR (4).zip](https://github.com/besteon/Ironmon-Tracker/files/8790580/KaizoFR.4.zip)

Here is an example of Guillotine not displaying that it doesn't work against Ghost types. The Haunter (Right Choice) has Guillotine.

I swear I am just going through seeds to find Counter... I just keep running into other moves along the way lol.

image

**Comment by Tapollo** [comment]
@bdjeffyp 

[KaizoFR (5).zip](https://github.com/besteon/Ironmon-Tracker/files/8790592/KaizoFR.5.zip)

Here is an example of Super Fang not displaying that it doesn't work against Ghost types. The Gastly (Left Choice) has Super Fang.

image

**Comment by bdjeffyp** [comment]
Thanks so much for all of this! I'll work on the fixes and retests today on stream.

**Comment by Tapollo** [comment]
I never got to counter but I am certain it would be an issue too. If needed
I can maybe get it by tomorrow.

**Comment by bdjeffyp** [comment]
No sweat, @Tapollo. I got it from here. Thanks again for the help in this.

**Comment by Tapollo** [comment]
What's your stream? I would love to check it out.

**Comment by bdjeffyp** [comment]
I'm https://www.twitch.tv/bdjeffyp

**Comment by bdjeffyp** [comment]
I figured out how to programmatically do this now after some thinking. In the check for `NOPOWER` moves, if the move is not a `STATUS` type attack, it does a check for ineffective moves by type:
- Normal <-> Ghost
- Fighting -> Ghost
- Psychic -> Dark
- Ground -> Flying
These instances will return 0.0 for the effectiveness, resulting in the red X appearing for the move. Now we don't have to check individual moves!

**Pull request merged**
