### PR TITLE
Fix Weight Move Calculation

### PR DESCRIPTION
**Pull request by Fellshadow**
hey, so fun fact i noticed a bug in the low kick calculation lol It only updates once. This is because the check was only looking for if the power was WT and then overwrote that power in the data itself, so in subsequent checks it would never be WT again

clip of the bug - https://clips.twitch.tv/MushyEnjoyablePeachAMPEnergy-brQVUTqCCSvyAe34

To fix this i re-used the calculation in the drawing side from the initial low kick calc i submitted but rewrote to use the utility function added by OnlySpaghettiCodes, which i've tested and know works (while switching back to WT after battle)

### CODE REVIEW

**Comment by Brian0255** [comment]
Good catch (and dumb oversight by me), just make sure you're also checking that Settings.tracker.CALCULATE_WEIGHT_BASED_DAMAGE = true

**Comment by Fellshadow** [comment]
oh yeah oops i must have forgotten to copy that over i'll get that in, one moment

**Comment by Fellshadow** [comment]
ok that's in there now, thanks for catching that

**Comment by Fellshadow** [comment]
small note, just tested with the setting off and the order of if statements i had broke it when the setting was set to false, fixed that

**Comment by Fellshadow** [comment]
OK so first of all my apologies for all the small commits and stuff, in my slight haste to get a fix out i wound up being a bit too lax in my testing

i have now tested this in and out of battle, with and without the setting enabled, and it should NOW be working 😩

**Comment by bdjeffyp** [comment]
Awesome! Thanks so much, both of you!

**Pull request merged**
